esphome:
  name: rice-cooker

external_components:
  source:
    type: local
    path: components

  
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true

# Make sure logging is not using the serial port
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: "8367"

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret wifi_password

captive_portal:

uart:
  - id: uart_bus
    tx_pin: GPIO33
    rx_pin: GPIO32
    baud_rate: 9600

ricecooker:
  id: ricecooker_id
  uart_id: uart_bus


switch:
  - platform: template
    name: "Power"
    id: power_switch
    icon: mdi:power
    lambda: |-
      return id(ricecooker_id).get_power();
    turn_on_action:
      - lambda:
          id(ricecooker_id).power_on();
    turn_off_action:
      - lambda:
          id(ricecooker_id).power_off();

sensor:
  - platform: template
    name: "Top sensor temperature"
    lambda: |-
      return id(ricecooker_id).get_top_temperature();
    update_interval: 1s
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement


  - platform: template
    name: "Bottom sensor temperature"
    lambda: |-
      return id(ricecooker_id).get_bottom_temperature();
    update_interval: 1s
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    state_class: measurement

number:
  - platform: template
    id: target_temperature
    name: "Target temperature"
    icon: mdi:thermometer
    min_value: 0
    max_value: 120
    mode: slider
    step: 1
    optimistic: true
    set_action:
      - lambda: |-
          id(ricecooker_id).set_temperature(x);