esphome:
  name: rice-cooker

external_components:
  source:
    type: local
    path: components

  
esp32:
  board: esp32dev
  framework:
    type: esp-idf
    version: recommended
    # Custom sdkconfig options
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
    # Advanced tweaking options
    advanced:
      ignore_efuse_mac_crc: true
      ignore_efuse_custom_mac: true



# Make sure logging is not using the serial port
logger:

# Enable Home Assistant API
api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: "8367"

wifi: 
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${name}
    password: !secret wifi_password

captive_portal:

uart:
  - id: uart_bus
    tx_pin: GPIO33
    rx_pin: GPIO32
    baud_rate: 9600

ricecooker:
  uart_id: uart_bus